name: Test Packages Configuration

on:
  push:
    branches: [ "main" ]
    paths:
      - '.github/workflows/**' # Chỉ chạy khi sửa chính file workflow
      - 'packages.txt'          # Hoặc khi sửa file packages

jobs:
  test-java-hadoop:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Java 11
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '11'

      - name: Install Hadoop
        run: |
          wget https://archive.apache.org/dist/hadoop/common/hadoop-3.3.6/hadoop-3.3.6.tar.gz
          tar -xzf hadoop-3.3.6.tar.gz

          echo "HADOOP_HOME=$PWD/hadoop-3.3.6" >> $GITHUB_ENV
          echo "$PWD/hadoop-3.3.6/bin" >> $GITHUB_PATH

      - name: Verify
        run: |
          java -version
          javac -version
          hadoop version
